library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(maps)
library(mapproj)
library(plotly)
soccer_df <- read.csv("https://raw.githubusercontent.com/tara-nguyen/english-premier-league-datasets-for-10-seasons/main/epldat10seasons/epl-allseasons-matchstats.csv")
